volumes:
  kafka:
    driver: ${VOLUMES_DRIVER}

services:

### KAFKA ##############################################
  kafka:
    build:
      context: ${KAFKA_HOST_PATH}
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
    container_name: ${KAFKA_CONTAINER_NAME}
    hostname: ${KAFKA_HOSTNAME}
    volumes:
      - "${DATA_HOST_PATH}/${KAFKA_CONTAINER_NAME}:/bitnami/kafka/data"
      - "${LOG_HOST_PATH}/${KAFKA_CONTAINER_NAME}:/bitnami/kafka/logs"
    ports:
      - "${KAFKA_HOST_PORT}:9094"
    environment:
      TZ: ${TZ}
      KAFKA_CFG_NODE_ID: ${KAFKA_CFG_NODE_ID}
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "${KAFKA_CFG_NODE_ID}@${KAFKA_HOSTNAME}:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      backend:
        ipv4_address: ${KAFKA_BACKEND_IP}
